FROM nginx:alpine

COPY default.conf  /etc/nginx/conf.d/default.conf

##Client Binaries
RUN wget https://dl.k8s.io/v1.14.8/kubernetes-client-linux-amd64.tar.gz -O /usr/share/nginx/html/kubernetes-client-linux-amd64.tar.gz
##Server Binaries
RUN wget https://dl.k8s.io/v1.14.8/kubernetes-server-linux-amd64.tar.gz -O /usr/share/nginx/html/kubernetes-server-linux-amd64.tar.gz
##Node Binaries
RUN wget https://dl.k8s.io/v1.14.8/kubernetes-node-linux-amd64.tar.gz -O /usr/share/nginx/html/kubernetes-node-linux-amd64.tar.gz

RUN echo "v1.14.8" > /usr/share/nginx/html/v1.14.8.txt

